---
# tasks file for roles/zfs-setup
- name: Install zfs-utils
  become: true
  package:
    name: zfsutils-linux
    state: present

- name: manage_zfs | checking existing zpool(s)
  ansible.builtin.shell: "zpool list | awk 'FNR >1' | awk '{print $1}'"
  changed_when: false
  register: zpools
  check_mode: no
  when: zfs_pools is defined

- name: manage_zfs | Gather ZPool Status
  ansible.builtin.shell: zpool status
  changed_when: false
  register: zpool_devices
  check_mode: no
  when: zfs_pools is defined

- name: manage_zfs | creating basic zpool(s)
  become: true
  ansible.builtin.command: "zpool create {{ '-o '+ item.options.items() |map('join', '=') | join (' -o ') if item.options is defined else '' }} {{ item.name }} {{ item.devices|join (' ') }}"
  register: zpool_created
  with_items: "{{ zfs_pools }}"
  when: >
        zfs_pools is defined and
        zfs_create_pools and
        (item.type == "basic" and
        item.name not in zpools.stdout and
        item.state == "present") and
        item.devices[0] not in zpool_devices.stdout and
        item.action|lower == "create"

- name: Create root filesystem mount directory
  become: true
  ansible.builtin.file:
    path: /shares
    state: directory

- name: Create a new file system called sharing in pool tank and mount to /shares
  become: true
  community.general.zfs:
    name: tank/sharing
    state: present
    extra_zfs_properties: 
      mountpoint: /shares

