---

- name: Install zfs-utils
  become: true
  package:
    name: zfsutils-linux
    state: present

- name: Install nfs-server
  become: true
  package:
    name: nfs-kernel-server
    state: present
  when: >
        zfs_enable_nfs is defined and
        zfs_enable_nfs

# Install samba server