#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/generate_markdown

- name: Debug vars.yml
  debug:
    var: readme

- name: Generate markdown file from chosen template
  become: true
  ansible.builtin.template:
    src: "{{ template_source }}"
    dest: "{{ output_path }}"