---
# tasks file for roles/hardlink
- name: Ensure the target config file is removed (if it exists)
  file:
    path: "{{ item.config_file }}"
    state: absent
  loop: "{{ services }}"

- name: Create a hardlink from /configs to the service config location
  command: ln "{{ item.source_file }}" "{{ item.config_file }}"
  loop: "{{ services }}"
