---
# tasks file for roles/smb-setup

- name: Install samba server
  become: true
  package:
    name: samba
    state: present

# Add write access group
# Add samba system user
# Add samba user with password
# Permission folder correctly for group access
# Add "public: yes" to smb.conf for guest read permissions



- name: Enable and start samba service
  become: true
  ansible.builtin.systemd:
    name: smbd
    enabled: yes
    state: started

- name: Generate /etc/samba/smb.conf from template
  become: true
  template:
    src: smb.conf.j2
    dest: /etc/samba/smb.conf
    owner: root
    group: root
    mode: '0644'
  notify: Restart smbd
  tags: config