---
#- name: Install samba server
#  become: true
#  package:
#    name: samba
#    state: present
#    update_cache: true

- name: Ensure group "smbwriters" exists
  become: true
  ansible.builtin.group:
    name: smbwriters
    state: present

- name: Add the system user 'velcro' for write access to smb shares
  become: true
  ansible.builtin.user:
    name: velcro
    shell: /bin/bash
    groups: smbwriters
    append: yes


