---
- name: Test Ansible Vault Variables
  hosts: localhost
  gather_facts: no
  vars_files:
    - vault.yaml
  tasks:
    - name: Debug ansible_ssh_password
      debug:
        msg: "The SSH password is: {{ ansible_ssh_password }}"

    - name: Debug ansible_ssh_private_key_file
      debug:
        msg: "The SSH private key file is: {{ ansible_ssh_private_key_file }}"
