@startuml deployment_context
title Deployment Context

cloud Internet {

    component "Public IP Lookup Service"

    component "Cloudflare API"

}

package "Home Network" {

    node "Host Server" {

        component "DDNS Service"

    }

}

"DDNS Service" --> "Public IP Lookup Service"
"DDNS Service" --> "Cloudflare API"
@enduml