@startuml deployment
title Deployment

cloud Internet {

    component "Public IP Service"

    component "Cloudflare API"

}

package "Home Network" {

    node "Host Server" {

        component "DDNS Service"

    }

}

"DDNS Service" --> "Public IP Service"
"DDNS Service" --> "Cloudflare API"


@enduml