@startuml synchronization_lifecycle
title Dynamic DNS Synchronization

actor "DDNS Service" as service

note over service
Periodically checks the
public IP address to
ensure external DNS
remains accurate.
end note

participant "Public IP Lookup Service" as website
participant "Cloudflare API" as api

activate service
service -> website : Public IP Request
activate website

website -> service : Public IP
deactivate website

note over service
Compares received IP
against cached value 
and only updates if 
value has changed.
end note

alt Public IP Changed

    
    service -> api : Update DNS record
    activate api

    api -> service: Update Successful
    deactivate api

else Public IP Unchanged
    
    note over service
    No action as cached
    public IP matches
    current value.
    end note

end

deactivate service

@enduml