services:
  # Jellyfin - Media Server
  jellyfin:
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    networks:
      - default
    security_opt:
      - no-new-privileges:true
    restart: always
    # profiles: ["media", "all"]
    user: $PUID:$PGID
    #group_add:
    # - "$RENDERGROUP" # Group id of render group in VM for access to graphics card.
    #devices:
    #  - /dev/dri/renderD128:/dev/dri/renderD128 # for harware transcoding
    ports:
      - "8096:8096"
      # - "8920:8920" # Emby also uses same port if running both
    environment:
      UMASK_SET: 022
      TZ: $TZ
    volumes:
      - $DOCKERDIR/appdata/jellyfin:/config
      - $DATADIR/data/media:/data/media
