- hosts: localhost
  gather_facts: false
  become: yes
  vars_files: 
    - generate_markdown_vars.yml
  tasks:
    - name: create README for specified role
      include_role:
        name: mathat13.role_book.generate_markdown

    - name: print role path
      debug:
        var: playbook_dir
