zfs_filesystems:
  - name: share-root
    pool: tank
    state: present
    options:
      atime: off
      # on | off (default) | lzjb | gzip | gzip-1 | gzip-2 | gzip-3 | gzip-4 | gzip-5 | gzip-6 | gzip-7 | gzip-8 | gzip-9 | lz4 | zle
      compression: lz4
      # latency (default) | throughput
      logbias: latency
      # Define an alternate mountpoint
      mountpoint: /shares
      # all (default) | none | metadata
      primarycache: all
      quota: 3G
      refquota: none
      # Defines recordsize.. 16K | 32K | 64K | 128K (default) | and etc.
      recordsize: 16K
      # sharenfs: "rw=@192.168.1.0/24"
      sharesmb: on
      # standard (default) | always | disabled    sync: disabled
      # Controls whether the snapshots devices of zvol's are hidden or visible. hidden (default) | visible
      snapdev: visible
      # Controls whether the .zfs directory is hidden or visible in the root of the file system. hidden (default) | visible
      snapdir: visible