---
samba_users:
  - name: velcro
    password: ovelcr

samba_shares:
 - name: test1
   path: /test1
   comment: "back to it"
   directory_mask: "0770"
   create_mask: "0660"
 - name: test2
   path: /test2
   browseable: true
   valid_users: acrobat
   force_user: acrobat

samba_settings:
  samba_workgroup: smelly
  directory_mask: "0775"
  create_mask: "0664"
  browseable: true