---
#- name: Verify packages are installed correctly
#  hosts: all
#  gather_facts: false
#  tasks:
#    - name: Gather the package facts
#      ansible.builtin.package_facts:
#        manager: auto
#
#    - name: Check samba in packages
#      assert:
#        that:
#          - "'samba' in ansible_facts.packages"

- name: Verify system user created and in correct group
  hosts: all
  gather_facts: false
  tasks:
    - name: Get list of groups
      ansible.builtin.command: getent group
      register: group_list
      changed_when: false

    - name: Get list of users
      ansible.builtin.command: getent passwd
      register: user_list
      changed_when: false

    - name: Get groups user is a part of
      ansible.builtin.command: groups velcro
      register: user_groups
      changed_when: false

    
    - name: Check group created successfully
      assert:
        that:
          - "'smbwriters' in group_list.stdout"

    - name: Check user created successfully
      assert:
        that:
          - "'velcro' in user_list.stdout"

    - name: Check user in expected group
      assert:
        that:
          - "'smbwriters' in user_groups.stdout"

- name: Verify smb user set up correctly
  hosts: all
  gather_facts: false
  tasks:
    - name: smb user database
      ansible.builtin.shell: 'pdbedit -L'
      register: smb_user_db
      changed_when: false

    - name: check all users in smb_user_db
      assert:
        that:
          - "{{ item.name }} in smb_user_db.stdout"
      loop: "{{ samba_users }}"
